name: Deploy to EC2

on:
  push:
    branches: [ feat/aws ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Build JAR
        run: ./gradlew clean build

      - name: Upload JAR to EC2 (overwrite exact path)
        uses: appleboy/scp-action@v0.1.4
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ec2-user
          key: ${{ secrets.EC2_SSH_KEY }}
          source: "build/libs/backend-0.0.1-SNAPSHOT.jar"
          target: "/home/ec2-user"
          overwrite: true
          strip_components: 2
          debug: true

      - name: Kill Existing Spring Boot Process
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ec2-user
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            echo "기존 프로세스 종료"
            PID=$(pgrep -f 'java -jar') && sudo kill -9 $PID || echo "No process to kill"

      - name: Start Spring Boot Application
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ec2-user
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            echo "JAR 파일 확인"
            ls -lh /home/ec2-user/backend-0.0.1-SNAPSHOT.jar || echo "파일 없음"

            echo "Java 버전 확인"
            java -version || echo "Java 없음"

            echo "새 앱 실행 중..."
            nohup java -jar /home/ec2-user/backend-0.0.1-SNAPSHOT.jar > log.txt 2>&1 &

            sleep 5

            echo "실행 로그:"
            tail -n 30 /home/ec2-user/log.txt
